REM PROJECT EULER PROBLEM 20

REM USE DECIMAL ARRAYS IN LITTLE
REM ENDIAN WITH 200 ELEMENTS FOR UP
REM TO 200 DECIMAL DIGITS

REM INITIALIZE A TO 100 AND C TO 99
DIM A%(200)
C%=99
A%(3)=1

REM MULTIPLY A BY C BY REPEATEDLY
REM ADDING A TO B AND FINALLY COPY B
REM INTO A AND CLEAR B

REM MULTIPLY A BY C AND DECREMENT C
FOR X%=1 TO C%-1
  PRINT "MULTIPLYING BY " C%
  PROC_MULT
  C%=C%-1
NEXT X%

REM SUM DIGITS AND PRINT RESULT
SUM%=0
FOR I%=1 TO 200
  SUM%=SUM%+A%(I%)
NEXT I%
PRINT SUM%
END

DEF PROC_MULT
  CARRY%=0
  FOR I%=1 TO 200
      TMP%=A%(I%)*C%
      TMP%=TMP%+CARRY%
      A%(I%)=TMP% MOD 10
      CARRY%=TMP%/10
  NEXT I%
ENDPROC
